resource_group_name         = "kml_rg_main-357e61e19fa54ed6"
virtual_network_name        = "vnetprod019"
subnet_name                 = "subnet019"
public_ip_name              = "publicip019"
network_security_group_name = "nsgprod019"
network_interface_name      = "nicprod019"
linux_virtual_machine_name  = "linuxvm019"
